app: pkuphysu-wechat
stage: ${env:STAGE}
component: website
name: pkuphysu-wechat-static
inputs:
  src:
    src: ./
    dist: ./dist
    hook: npm run build
    index: index.html
  region: ap-shanghai
  zone: ap-shanghai-2
  bucket: pkuphysu-${env:STAGE}
  replace: true
  protocol: https
  env:
    # Tencent doesn't support `triggers[0]` yet.
    # It just doesn't get replaced
    API_DETAILS: ${output:${stage}:${app}:pkuphysu-wechat.triggers}
    APPID: ${env:APPID}
